######################################################################
# Automatically generated by qmake (3.0) gio feb 23 23:20:54 2017
######################################################################

TEMPLATE = app
TARGET = 1.5.1.2.x
INCLUDEPATH += .

# Input
SOURCES += temp.cpp
