######################################################################
# Automatically generated by qmake (3.0) mar mar 14 23:33:10 2017
######################################################################

TEMPLATE = app
TARGET = 5.12.4.x
INCLUDEPATH += .

QT += core

# Input
HEADERS += crypto.h
SOURCES += crypto.cpp main.cpp
