######################################################################
# Automatically generated by qmake (3.0) dom mar 12 23:40:34 2017
######################################################################

TEMPLATE = app
TARGET = 4.4.2.x
INCLUDEPATH += .

QT += core

# Input
HEADERS += contact.h contactfactory.h contactlist.h
SOURCES += contact.cpp contactfactory.cpp contactlist.cpp main.cpp
