######################################################################
# Automatically generated by qmake (3.0) ven feb 24 15:00:45 2017
######################################################################

TEMPLATE = app
TARGET = 1.13.3.x
INCLUDEPATH += .

LIBS += 

QT += core widgets

# Input
SOURCES += temp.cpp
