######################################################################
# Automatically generated by qmake (3.0) dom feb 26 11:57:46 2017
######################################################################

TEMPLATE = app
TARGET = 3.4.1.x
INCLUDEPATH += .

QT += core widgets

# Input
SOURCES += converter.cpp
