######################################################################
# Automatically generated by qmake (3.0) gio feb 23 23:22:33 2017
######################################################################

TEMPLATE = app
TARGET = 1.5.1.1.x
INCLUDEPATH += .

LIBS += -lgmp -lgmpxx

# Input
SOURCES += fac2.cpp
